#!/bin/bash

## Display all available commands and aliases from bash_profile

show_help() {
    echo ""
    echo "=== bash_profile commands ==="
    echo ""

    echo "--- Navigation ---"
    echo "  bus         cd /mnt/user/ (linux)"
    echo "  bdow        cd /mnt/user/Download/ (linux)"
    if [ "$bash_profile_os" = "macos" ]; then
    echo "  bpro        cd ~/Projects/"
    echo "  bdesk       cd ~/Desktop/"
    echo "  bdow_mac    cd ~/Downloads/"
    fi
    echo ""

    echo "--- Files & Directories ---"
    echo "  lsa         ls -AlhF (detailed listing)"
    echo "  tre         tree -ah (tree view with hidden files)"
    echo "  dul         du -h --max-depth=1 (disk usage summary)"
    echo "  c           clear"
    echo "  untar       tar -zxvf (extract archive)"
    command -v eza &>/dev/null && echo "  ll          eza detailed listing with git status"
    command -v eza &>/dev/null && echo "  lt          eza tree view (2 levels)"
    command -v eza &>/dev/null && echo "  llt         eza detailed tree view"
    command -v eza &>/dev/null && echo "  lr          eza sorted by modified (recent last)"
    command -v bat &>/dev/null || command -v batcat &>/dev/null && echo "  catx        bat with syntax highlighting"
    command -v bat &>/dev/null || command -v batcat &>/dev/null && echo "  catp        bat plain (no line numbers)"
    command -v dust &>/dev/null && echo "  dux         dust (visual disk usage)"
    command -v fd &>/dev/null || command -v fdfind &>/dev/null && echo "  fdf         fd --type f (find files)"
    command -v fd &>/dev/null || command -v fdfind &>/dev/null && echo "  fdd         fd --type d (find directories)"
    command -v rg &>/dev/null && echo "  rgg         ripgrep smart-case search"
    command -v yazi &>/dev/null && echo "  yy          yazi file manager (cd's on exit)"
    echo ""

    echo "--- Git ---"
    echo "  gs          git status"
    echo "  gss         git status --short"
    echo "  gb          git branch (sorted by date)"
    echo "  gbs         git branch detailed (hash, message, author)"
    echo "  gc          git commit -p (interactive patch)"
    echo "  gd          git diff"
    echo "  gda         git diff HEAD"
    echo "  glg         git log (decorated, detailed)"
    echo "  glgs        git log --graph --oneline --all"
    echo "  gst         git stash"
    echo "  gsta        git stash apply"
    echo "  gstd        git stash drop"
    echo "  gstl        git stash list"
    echo "  gstp        git stash pop"
    echo "  gsts        git stash push -m (save with message)"
    echo "  gsw         git switch (modern checkout)"
    echo "  gswc        git switch -c (create + switch)"
    echo "  grs         git restore (discard changes)"
    echo "  grss        git restore --staged (unstage)"
    echo "  gfp         git fetch --all --prune"
    echo "  grom        git rebase origin/main"
    echo "  grod        git rebase origin/dev"
    echo "  gcp         git cherry-pick"
    echo "  gwip        git add -A && commit 'WIP'"
    echo "  gundo       git reset --soft HEAD~1"
    echo "  gclean      delete merged branches (keeps main/master/dev)"
    command -v lazygit &>/dev/null && echo "  lzg         lazygit (terminal UI)"
    command -v difft &>/dev/null && echo "  gdft        syntax-aware git diff (difftastic)"
    command -v difft &>/dev/null && echo "  gdfts       syntax-aware git diff --staged"
    command -v difft &>/dev/null && echo "  difft       difftastic standalone: difft file1 file2"
    command -v onefetch &>/dev/null && echo "  repoinfo    git repo info card (onefetch)"
    echo ""

    if command -v gh &>/dev/null; then
    echo "--- GitHub CLI ---"
    echo "  ghpr        gh pr list"
    echo "  ghprc       gh pr create"
    echo "  ghprv       gh pr view --web"
    echo "  ghprd       gh pr diff"
    echo "  ghis        gh issue list"
    echo "  ghisc       gh issue create"
    echo "  ghisv       gh issue view --web"
    echo "  ghrc        gh repo clone"
    echo "  ghpro       gh pr checkout"
    echo "  ghprm       gh pr merge"
    echo "  ghprs       gh pr status"
    echo "  ghrun       gh run list (CI runs)"
    echo "  ghrunv      gh run view"
    echo "  ghrunw      gh run watch (live CI)"
    echo "  ghrv        gh repo view --web"
    echo ""
    fi

    echo "--- Docker ---"
    if command -v docker &>/dev/null; then
    echo "  dps         docker ps (formatted)"
    echo "  dpsa        docker ps -a (formatted)"
    echo "  dlogs       docker logs -f"
    echo "  dstop       stop all running containers"
    echo "  dprune      docker system prune"
    echo "  dex <name>  docker exec -it <name> bash"
    fi
    if command -v docker-compose &>/dev/null || docker compose version &>/dev/null 2>&1; then
    echo "  dcu         docker compose up -d"
    echo "  dcd         docker compose down"
    echo "  dcl         docker compose logs -f"
    echo "  dcr         docker compose restart"
    echo "  dcps        docker compose ps"
    fi
    command -v lazydocker &>/dev/null && echo "  lzd         lazydocker (terminal UI)"
    echo ""

    echo "--- Network ---"
    echo "  ip <addr>   full info for IP (own IP if no arg)"
    echo "  ipgeo       geolocation"
    echo "  iporg       organization"
    echo "  ipe         external IP (just the address)"
    echo "  ipeinfo     external IP full info"
    echo "  ipegeo      external IP geolocation"
    echo "  ipeorg      external IP organization"
    echo "  ipi         local network IPs"
    echo "  ping        ping -c 5"
    echo "  url_info    URL timing breakdown (curl)"
    echo "  bench_netspeed  network speed test"
    command -v mtr &>/dev/null && echo "  pingt       mtr traceroute report"
    command -v gping &>/dev/null && echo "  gping       ping with live graph"
    command -v trip &>/dev/null && echo "  sudo trip   network diagnostic TUI (trippy)"
    command -v http &>/dev/null && echo "  httpp       httpie with headers+body"
    command -v xh &>/dev/null && echo "  xhp         xh (faster httpie) with headers+body"
    echo ""

    echo "--- Utilities ---"
    echo "  bphelp      show this help"
    echo "  bpinstall   install modern CLI tools (brew/apt/dnf/pacman)"
    echo "  bpupdate    pull latest + re-install"
    command -v delta &>/dev/null && echo "  bpdelta     configure delta as git diff pager"
    echo "  genpass     generate random password (default 20 chars)"
    command -v fastfetch &>/dev/null && echo "  osinfo      system info (fastfetch)"
    command -v hyperfine &>/dev/null && echo "  hyperfine   command benchmarking"
    command -v procs &>/dev/null && echo "  procs       modern ps (color, search, tree)"
    command -v btm &>/dev/null && echo "  btm         modern top/htop (bottom)"
    command -v tldr &>/dev/null && echo "  tldr        simplified man pages"
    command -v jq &>/dev/null && echo "  jq          JSON processor"
    command -v yq &>/dev/null && echo "  yq          YAML/TOML processor"
    command -v tokei &>/dev/null && echo "  tokei       code line counter (200+ languages)"
    command -v glow &>/dev/null && echo "  glow        render markdown in terminal"
    echo ""

    echo "--- Prompt ---"
    if command -v starship &>/dev/null; then
    echo "  Using: starship (cross-shell prompt)"
    else
    echo "  Using: custom PS1 with git branch display"
    echo "  Tip:   install starship for a richer prompt (brew install starship)"
    fi
    echo ""
}

show_help
